# Safety Policy Configuration for SAMO-DL
# This policy controls how Safety CLI handles vulnerability scanning in CI/CD
# Version: Safety v3.x compatible

version: "3.0"

# Project metadata
project:
  name: "SAMO-DL"
  description: "Deep Learning project with security-first approach"

# Scanning configuration
scanning:
  # Fail the scan based on vulnerability severity
  # Exit code 64 is returned when vulnerabilities exceed threshold
  fail_scan_with_exit_code: 64
  
  # Severity levels to fail on (Safety v3 format)
  # Options: critical, high, medium, low, unknown
  fail_on_severity_levels:
    - critical
    - high
  
  # Continue scanning even if vulnerabilities are found
  # This ensures we get a complete report
  continue_on_vulnerability_error: true

# Vulnerability handling
vulnerabilities:
  # Ignore specific vulnerabilities by ID if needed
  # Format: vulnerability ID with optional expiry date
  ignore:
    # Example (uncomment to use):
    # - vulnerability_id: "51457"  # numpy vulnerability
    #   reason: "False positive - not applicable to our use case"
    #   expires: "2025-12-31"
  
  # Ignore entire packages if needed (use with caution)
  ignore_packages: []
    # Example:
    # - package_name: "some-package"
    #   reason: "Development only dependency"

# Environment-specific settings
environments:
  production:
    # Stricter settings for production
    fail_on_severity_levels:
      - critical
      - high
    continue_on_vulnerability_error: false
  
  development:
    # More lenient for development
    fail_on_severity_levels:
      - critical
    continue_on_vulnerability_error: true
  
  ci:
    # CI/CD specific settings (default)
    fail_on_severity_levels:
      - critical
      - high
    continue_on_vulnerability_error: true

# Reporting configuration
reporting:
  # Output format for reports
  format: "json"
  
  # Include detailed information
  detailed: true
  
  # Show only vulnerabilities (hide safe packages)
  only_vulnerabilities: false
  
  # Include remediation advice
  include_remediation: true

# Auto-fix configuration (use with caution)
auto_fix:
  # Do not auto-fix in CI - require manual review
  enabled: false
  
  # If enabled, only fix these severity levels
  fix_severity_levels:
    - critical

# Audit trail
audit:
  # Log all scans for compliance
  enabled: true
  
  # Include timestamp in reports
  include_timestamp: true
  
  # Include scanner version
  include_scanner_version: true

# Custom rules (optional)
custom_rules: []
  # Example:
  # - rule_id: "CUSTOM-001"
  #   description: "Ensure all ML packages are from trusted sources"
  #   severity: "high"
  #   pattern: "torch|tensorflow|transformers"
  #   action: "warn"