steps:
  # Build the Docker image with dynamic tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'deployment/docker/Dockerfile.optimized',
      '-t', 'gcr.io/$PROJECT_ID/emotion-detection-api:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/emotion-detection-api:latest',
      '.'
    ]
  
  # Deploy to Cloud Run with secure API key from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'emotion-detection-api',
      '--image', 'gcr.io/$PROJECT_ID/emotion-detection-api:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--max-instances', '10',
      '--set-env-vars', 'ADMIN_API_KEY=${_ADMIN_API_KEY}'
    ]
    secretEnv: ['ADMIN_API_KEY']

# Available images
images:
  - 'gcr.io/$PROJECT_ID/emotion-detection-api:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/emotion-detection-api:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Substitutions for dynamic values
substitutions:
  _ADMIN_API_KEY: 'YOUR_SECURE_API_KEY_HERE'

# Available secrets (set these in Cloud Build settings)
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/admin-api-key/versions/latest
      env: 'ADMIN_API_KEY'
