# Example Cloud Build configuration with custom values
# Copy this file to cloudbuild.yaml and modify as needed

steps:
  # Build the Docker image with dynamic tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'deployment/docker/Dockerfile.optimized',
      '-t', 'gcr.io/$PROJECT_ID/emotion-detection-api:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/emotion-detection-api:latest',
      '.'
    ]
  
  # Deploy to Cloud Run with parameterized configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'gcr.io/$PROJECT_ID/emotion-detection-api:$BUILD_ID',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '${_PORT}',
      '--memory', '${_MEMORY}',
      '--cpu', '${_CPU}',
      '--max-instances', '${_MAX_INSTANCES}'
    ]
    secretEnv: ['ADMIN_API_KEY']

# Available images
images:
  - 'gcr.io/$PROJECT_ID/emotion-detection-api:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/emotion-detection-api:latest'

# Build options
options:
  machineType: '${_MACHINE_TYPE}'
  diskSizeGb: ${_DISK_SIZE}
  logging: CLOUD_LOGGING_ONLY

# Substitutions for all configurable values
substitutions:
  # Service configuration
  _SERVICE_NAME: 'emotion-detection-api'
  _REGION: 'us-central1'
  _PORT: '8080'
  
  # Resource allocation (adjust based on your needs)
  _MEMORY: '2Gi'          # Options: 128Mi, 256Mi, 512Mi, 1Gi, 2Gi, 4Gi, 8Gi
  _CPU: '2'               # Options: 1, 2, 4, 6, 8
  _MAX_INSTANCES: '10'    # Adjust based on expected traffic
  
  # Build configuration
  _MACHINE_TYPE: 'E2_HIGHCPU_8'  # Options: E2_STANDARD_2, E2_HIGHCPU_4, E2_HIGHCPU_8
  _DISK_SIZE: '100'              # Disk size in GB

# Available secrets (set these in Cloud Build settings)
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/admin-api-key/versions/latest
      env: 'ADMIN_API_KEY'
