steps:
  # Pull latest image for build caching (allow failure if image doesn't exist)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/samo-unified-api:latest || exit 0

  # Build the Docker image with dynamic tag and caching
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--platform', 'linux/amd64',
      '--cache-from', 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/samo-unified-api:latest',
      '-f', 'Dockerfile.unified',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/samo-unified-api:$BUILD_ID',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/samo-unified-api:latest',
      '.'
    ]

  # Scan image for vulnerabilities
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'artifacts', 'docker', 'images', 'scan',
      'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/samo-unified-api:$BUILD_ID',
      '--region=us-central1'
    ]
  
  # Deploy to Cloud Run with parameterized configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/samo-unified-api:$BUILD_ID',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '${_PORT}',
      '--memory', '${_MEMORY}',
      '--cpu', '${_CPU}',
      '--max-instances', '${_MAX_INSTANCES}',
      '--set-env-vars', 'RATE_LIMIT_REQUESTS_PER_MINUTE=100,RATE_LIMIT_BURST_SIZE=20,RATE_LIMIT_MAX_CONCURRENT=10,RATE_LIMIT_RAPID_FIRE_THRESHOLD=20,RATE_LIMIT_SUSTAINED_THRESHOLD=150',
      '--set-env-vars', 'LOG_LEVEL=INFO,ENVIRONMENT=production',
      '--set-env-vars', 'EMOTION_MODEL_ID=0xmnrv/samo,TEXT_SUMMARIZER_MODEL=t5-small,VOICE_TRANSCRIBER_MODEL=base'
    ]
    secretEnv: ['ADMIN_API_KEY']

# Available images
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/samo-unified-api:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/samo-unified-api:latest'


# Substitutions for all configurable values
substitutions:
  # Service configuration
  _SERVICE_NAME: 'samo-unified-api'
  _REGION: 'us-central1'
  _PORT: '8080'
  
  # Resource allocation
  _MEMORY: '4Gi'
  _CPU: '2'
  _MAX_INSTANCES: '5'
  
  # Build configuration
  _MACHINE_TYPE: 'E2_HIGHCPU_8'
  _DISK_SIZE: '100'
  
  # Artifact Registry configuration
  _ARTIFACT_REPO: 'samo-dl'

# Available secrets (set these in Cloud Build settings)
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/admin-api-key/versions/latest
      env: 'ADMIN_API_KEY'