# environment.yml - Optimized for SAMO Deep Learning Track
# Focus: Minimize conflicts while maintaining compatibility
name: samo-dl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  # PyTorch ecosystem - let conda choose compatible versions within constraints
  - pytorch>=2.1.0,<2.2.0    # Allow patch updates for bug fixes
  - torchvision>=0.16.0,<0.17.0
  - torchaudio>=2.1.0,<2.2.0
  
  # Core ML libraries - more flexible versioning for better compatibility
  - transformers>=4.30.0,<5.0.0   # Major version 4.x with flexibility
  - datasets>=2.10.0,<3.0.0       # Allow minor updates within v2
  - tokenizers>=0.13.0,<1.0.0     # Stable tokenizer versions
  
  # Data processing essentials - stable but flexible
  - pandas>=2.0.0,<3.0.0
  - numpy>=1.24.0,<2.0.0
  - scikit-learn>=1.3.0,<2.0.0
  
  # Database and ORM
  - psycopg2>=2.9.0,<3.0.0       # PostgreSQL adapter
  - sqlalchemy>=2.0.0,<3.0.0     # SQL toolkit and ORM
  
  # Development and experimentation tools
  - jupyter>=1.0.0
  - ipykernel>=6.20.0
  - matplotlib>=3.7.0,<4.0.0
  - seaborn>=0.12.0,<1.0.0
  
  # Code quality and testing
  - black>=23.0.0,<24.0.0
  - pytest>=7.0.0,<8.0.0
  
  # API development for potential integration (minimal footprint)
  - fastapi>=0.100.0,<1.0.0
  - uvicorn>=0.20.0,<1.0.0
  - pydantic>=2.0.0,<3.0.0
  
  # Essential tools
  - pip
  - pip:
    # Pip-only packages with flexible versioning
    - accelerate>=0.20.0,<1.0.0
    - google-cloud-storage>=2.8.0,<3.0.0
    - google-cloud-aiplatform>=1.30.0,<2.0.0
    - openai>=1.0.0,<2.0.0
    - python-dotenv>=1.0.0,<2.0.0
    - pgvector>=0.2.0,<1.0.0     # PostgreSQL pgvector extension Python client
    - alembic>=1.11.0,<2.0.0     # Database migration tool
    - nodejs>=0.1.1,<1.0.0       # For running Prisma operations