# environment.yml
name: samo-dl
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  
  # PyTorch CPU-only for M4 MacBook (ARM64 architecture)
  - pytorch=2.1.0  # Will automatically use CPU version on ARM Mac
  - torchvision=0.16.0
  - torchaudio=2.1.0
  
  # Core ML libraries for development and testing
  - transformers=4.35.0  # Hugging Face models
  - datasets=2.14.0      # Dataset loading and processing
  - tokenizers=0.15.0    # Fast tokenization
  - accelerate=0.24.0    # Training utilities (works with CPU too)
  
  # Data processing essentials
  - pandas=2.1.0
  - numpy=1.25.0
  - scikit-learn=1.3.0
  
  # Development and experimentation tools
  - jupyter=1.0.0        # For initial exploration
  - ipykernel=6.25.0     # Jupyter kernel
  - matplotlib=3.7.0     # Plotting and visualization
  - seaborn=0.12.0       # Statistical visualization
  
  # Code quality and testing
  - black=23.7.0         # Code formatting
  - pytest=7.4.0         # Testing framework
  
  # API development for integration with Web Development track
  - fastapi=0.104.0      # Modern Python API framework
  - uvicorn=0.24.0       # ASGI server for FastAPI
  - pydantic=2.4.0       # Data validation
  
  # Cloud integration and deployment
  - pip
  - pip:
    - google-cloud-storage==2.10.0     # GCP file storage
    - google-cloud-aiplatform==1.36.0  # Vertex AI for cloud training
    - openai==1.3.0                    # Whisper API integration
    - python-dotenv==1.0.0             # Environment variable management
