name: samo-dl-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - libsndfile
  - portaudio
  - curl
  - pip:
      # API/runtime dependencies (align with dependencies/requirements-api.txt)
      - fastapi==0.116.1
      - uvicorn[standard]==0.35.0
      - python-multipart==0.0.18
      - pydantic==2.11.7
      - PyJWT==2.8.0
      - sqlalchemy==2.0.36
      - psycopg2-binary==2.9.10
      - pgvector==0.3.6
      - redis==5.0.8
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - requests==2.32.4
      - certifi==2024.12.14
      - click==8.1.8
      - rich==13.9.4
      - loguru==0.7.2
      - prometheus-client==0.20.0
      
      # Dev/test dependencies (from dependencies/requirements-dev.txt)
      - pytest==8.3.2
      - pytest-xdist==3.6.1
      - pytest-asyncio==0.21.0
      - pytest-cov==6.2.1
      - ruff==0.6.9
      - black==23.7.0
      - mypy==1.10.0
      - bandit==1.7.9
      - pre-commit==3.3.0