name: samo-dl-stable
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ffmpeg
  - libsndfile
  - portaudio
  - curl
  - pip:
      - fastapi==0.116.1
      - uvicorn==0.35.0
      - pydantic==2.11.7
      - PyJWT==2.8.0
      - Flask==3.0.3
      - requests==2.32.4
      - psutil==5.9.8
      - python-multipart==0.0.9
      - numpy==1.26.4
      - transformers==4.55.0
      - sentencepiece==0.1.99
      - torch==2.6.0  # SECURITY: Updated from 2.2.2 to fix CVE torch.load RCE vulnerability
      - openai-whisper==20250625
      - pydub==0.25.1
      - jiwer==3.0.3
      - websockets==12.0
      - prometheus-client==0.20.0
      - ruff==0.6.9
      - pytest==8.3.2
      - pytest-xdist==3.6.1
      - bandit==1.7.9
      - safety==3.2.3
      - mypy==1.10.0
      - httpx==0.27.2
      - python-dotenv==1.0.1
      - psycopg2-binary==2.9.9
