steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/71517823771/samo-dl/samo-emotion-api-secure', '-f', 'Dockerfile.secure', '.']
images:
  - 'us-central1-docker.pkg.dev/71517823771/samo-dl/samo-emotion-api-secure'
