name: samo-dl-stable
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - libsndfile
  - portaudio
  - curl
  - pip:
      # API/runtime dependencies only (align with dependencies/requirements-api.txt)
      - fastapi==0.116.1
      - uvicorn[standard]==0.35.0
      - python-multipart==0.0.18
      - pydantic==2.11.7
      - PyJWT==2.8.0
      - sqlalchemy==2.0.36
      - psycopg2-binary==2.9.10
      - pgvector==0.3.6
      - redis==5.0.8
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - requests==2.32.4
      - certifi==2024.12.14
      - click==8.1.8
      - rich==13.9.4
      - loguru==0.7.2
      - prometheus-client==0.20.0

# Note: For development, use environment.dev.yml
# For ML training/inference, use environment.ml.yml
