# Model Monitoring Configuration for REQ-DL-010
# SAMO Deep Learning - Real-time Model Performance Tracking

monitoring:
  # General settings
  monitor_interval: 300  # 5 minutes
  alert_threshold: 0.1   # 10% performance degradation
  drift_threshold: 0.05  # 5% data drift
  retrain_threshold: 0.15  # 15% degradation triggers retraining
  
  # Performance tracking
  performance:
    window_size: 100  # Sliding window for metrics
    metrics_to_track:
      - f1_score
      - precision
      - recall
      - inference_time_ms
      - throughput_rps
      - memory_usage_mb
      - gpu_utilization
      - cpu_utilization
    
  # Data drift detection
  drift_detection:
    reference_data_path: "data/processed/reference_data.csv"
    features_to_monitor:
      - text_length
      - emotion_distribution
      - vocabulary_diversity
    statistical_tests:
      - ks_test
      - chi_square_test
      - wasserstein_distance
    
  # Alerting configuration
  alerts:
    email_enabled: false
    slack_webhook: null
    log_level: "INFO"
    alert_channels:
      - console
      - file
    
  # Model health checks
  health_checks:
    inference_latency_threshold: 200  # ms
    memory_usage_threshold: 4096      # MB
    gpu_utilization_threshold: 0.9    # 90%
    cpu_utilization_threshold: 0.8    # 80%
    
  # Automated retraining
  retraining:
    enabled: true
    trigger_conditions:
      - performance_degradation: 0.15
      - data_drift: 0.1
      - time_based: "7d"  # Retrain every 7 days
    retraining_script: "scripts/retrain_model.py"
    backup_models: true
    
  # Storage configuration
  storage:
    metrics_database: "logs/model_metrics.db"
    alert_log: "logs/alerts.log"
    performance_log: "logs/performance.log"
    drift_log: "logs/drift.log"
    
  # Dashboard configuration
  dashboard:
    enabled: true
    port: 8080
    refresh_interval: 60  # seconds
    metrics_retention_days: 30 