# SAMO-DL Emotion Detection Configuration
# Optimized parameters for journal entry emotion analysis

# Model Configuration
model:
  name: "bert-base-uncased"  # Robust BERT model for emotion understanding
  device: null               # Auto-detect (CPU/GPU)

# Emotion Detection Parameters
emotion_detection:
  # Number of emotion categories (27 GoEmotions + neutral)
  num_emotions: 28
  
  # Prediction threshold for binary classification
  prediction_threshold: 0.6  # Updated from 0.5 for better calibration
  
  # Temperature scaling for calibrated predictions
  temperature: 1.0
  
  # Top-k emotions to return per prediction
  top_k: 5

# Model Architecture
architecture:
  # BERT configuration
  hidden_dropout_prob: 0.3      # Dropout for BERT hidden layers
  attention_probs_dropout_prob: 0.3  # Dropout for attention layers
  
  # Classification head configuration
  classifier_dropout_prob: 0.5  # Dropout for classification layers
  
  # Freezing strategy
  freeze_bert_layers: 6         # Number of BERT layers to freeze initially
  
  # Class balancing
  use_class_weights: true       # Enable class weight balancing

# Training Configuration
training:
  # Batch sizes
  train_batch_size: 16
  eval_batch_size: 32
  
  # Learning rates
  bert_learning_rate: 2e-5      # Lower LR for BERT (fine-tuning)
  classifier_learning_rate: 5e-4  # Higher LR for classification head
  
  # Training epochs
  num_epochs: 10
  warmup_steps: 100
  
  # Gradient settings
  max_grad_norm: 1.0
  gradient_accumulation_steps: 1
  
  # Early stopping
  early_stopping_patience: 3
  early_stopping_threshold: 0.01

# Data Processing
data:
  # Text processing
  max_length: 512               # Maximum sequence length
  truncation: true
  padding: "max_length"
  
  # Data augmentation
  enable_augmentation: false    # Disable for now, can be enabled later
  
  # Validation split
  validation_split: 0.2
  test_split: 0.1

# Evaluation Configuration
evaluation:
  # Metrics to compute
  metrics:
    - "precision"
    - "recall"
    - "f1_micro"
    - "f1_macro"
    - "accuracy"
  
  # Evaluation threshold (lowered to capture more predictions)
  threshold: 0.2
  
  # Top-k evaluation
  top_k_evaluation: true
  top_k_values: [1, 3, 5]

# Logging and Monitoring
logging:
  level: "INFO"
  log_interval: 100             # Log every N steps
  save_interval: 1000           # Save checkpoint every N steps
  
  # TensorBoard logging
  enable_tensorboard: true
  log_dir: "logs/emotion_detection"

# Model Saving
model_saving:
  # Save directory
  save_dir: "models/emotion_detection"
  
  # Save best model based on metric
  save_best_metric: "f1_macro"
  
  # Save checkpoints
  save_checkpoints: true
  checkpoint_interval: 1        # Save every N epochs

# Performance Optimization
performance:
  # Mixed precision training
  use_amp: true                 # Automatic Mixed Precision
  
  # Data loading
  num_workers: 4
  pin_memory: true
  
  # Memory optimization
  gradient_checkpointing: false  # Can be enabled for memory savings
  
  # Inference optimization
  use_torchscript: false        # Can be enabled for faster inference

# SAMO-Specific Optimizations
samo_optimizations:
  # Journal entry specific settings
  journal_entry_mode: true
  
  # Emotional context awareness
  context_awareness: true
  
  # Multi-label prediction
  multi_label_mode: true
  
  # Confidence calibration
  calibration_enabled: true
  
  # Emotion intensity scaling
  intensity_scaling: true

# Error Handling
error_handling:
  # Retry settings
  max_retries: 3
  retry_delay: 1.0
  
  # Fallback behavior
  fallback_to_cpu: true
  graceful_degradation: true
  
  # Logging errors
  log_errors: true
  error_log_file: "logs/emotion_detection_errors.log"

# Security and Privacy
security:
  # Input sanitization
  sanitize_input: true
  
  # Output filtering
  filter_sensitive_emotions: false  # Can be enabled for privacy
  
  # Rate limiting
  rate_limit_requests: 1000    # Requests per minute
  
  # Data privacy
  anonymize_predictions: false  # Can be enabled for privacy

# Development and Debugging
development:
  # Debug mode
  debug_mode: false
  
  # Verbose logging
  verbose: false
  
  # Test mode
  test_mode: false
  
  # Profiling
  enable_profiling: false
  profile_steps: 100
