/**
 * Server-side API Configuration Endpoint
 * This file can be served by a web server to provide runtime configuration
 * without exposing sensitive URLs in client-side code
 * 
 * Usage: Serve this as /api/config or similar endpoint
 * The client will fetch this configuration at runtime
 */

// This would typically be generated by your build process or server
const SERVER_CONFIG = {
    baseURL: process.env.API_BASE_URL || '/api',
    apiKey: process.env.API_KEY || null,
    timeout: parseInt(process.env.API_TIMEOUT || '30000', 10),
    retryAttempts: parseInt(process.env.API_RETRY_ATTEMPTS || '3', 10),
    environment: process.env.NODE_ENV || 'development',
    version: process.env.APP_VERSION || '1.0.0'
};

// Express.js endpoint example
if (typeof module !== 'undefined' && module.exports) {
    module.exports = (req, res) => {
        res.setHeader('Content-Type', 'application/json');
        res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
        res.json(SERVER_CONFIG);
    };
}

// For direct serving
if (typeof window !== 'undefined') {
    window.SERVER_CONFIG = SERVER_CONFIG;
}
